In [1]:
import numpy as np

In [3]:
a = np.array([[2, 3, 4], [1, 2, 5], [5, 4, 8]])
b = np.array([[2, 2, 8], [4, 3, 2]])

In [16]:
print(a.shape)
a

(3, 3)


array([[2, 3, 4],
       [1, 2, 5],
       [5, 4, 8]])

In [17]:
print(b.shape)
b

(2, 3)


array([[2, 2, 8],
       [4, 3, 2]])

In [33]:
c = np.zeros((b.shape[0], a.shape[0]))

for i in range(len(b)):
    for j in range(len(a)):
        c[i, j] = np.sum((a[j, :] - b[i, :])**2)
c        

array([[17., 10., 13.],
       [ 8., 19., 38.]])

In [34]:
d = np.zeros((b.shape[0], a.shape[0]))

for i in range(len(b)):
    d[i, ] = np.sum((a - b[i, :])**2, axis = 1)
    
d

array([[17., 10., 13.],
       [ 8., 19., 38.]])

In [35]:
dists = -2 * np.dot(b, a.T) + np.sum(a**2,    axis=1) + np.sum(b**2, axis=1)[:, np.newaxis]
dists

array([[17, 10, 13],
       [ 8, 19, 38]])

In [38]:
X_train = np.array([[2, 3, 4], [1, 2, 5], [5, 4, 8], [2, 3, 4], [1, 2, 5], [5, 4, 8], [2, 3, 4], [1, 2, 5], [5, 4, 8]])
y_train = np.array(range(9))
num_folds = 3
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]
X_train_folds = []
y_train_folds = []
X_train_folds = np.array_split(X_train, num_folds)
y_train_folds = np.array_split(y_train, num_folds)



for i_fold in range(num_folds):
    y_train_list = [x for i, x in enumerate(y_train_folds) if i != i_fold]
    X_train_list = [x for i, x in enumerate(X_train_folds) if i != i_fold]
    y_train = np.concatenate(y_train_list)
    X_train = np.concatenate(X_train_list)
    y_test = y_train_folds[i_fold]
    X_test = X_train_folds[i_fold]
    classifier.train(X_train, y_train)
    dists = classifier.compute_distances_no_loops(X_test)
    for k in k_choices:
        y_test_pred = classifier.predict_labels(dists, k = k)
        num_correct = np.sum(y_test_pred == y_test)
        accuracy = float(num_correct) / num_test
        if k in k_to_accuracies:
            k_to_accuracies[k].append(accuracy)
        else:
            k_to_accuracies[k] = [accuracy]

print(y_train.shape)
print(X_train.shape)
print(y_test.shape)
print(X_test.shape)

(6,)
(6, 3)
(3,)
(3, 3)


In [39]:
y_train

array([0, 1, 2, 3, 4, 5])

In [40]:
X_train

array([[2, 3, 4],
       [1, 2, 5],
       [5, 4, 8],
       [2, 3, 4],
       [1, 2, 5],
       [5, 4, 8]])

In [41]:
y_test

array([6, 7, 8])

In [42]:
X_test

array([[2, 3, 4],
       [1, 2, 5],
       [5, 4, 8]])

In [ ]:
for i_fold in range(num_folds):

    y_train = np.concatenate(y_train_list)
    X_train = np.concatenate(X_train_folds[])
    y_test = y_train_folds[i_fold]
    X_test = X_train_folds[i_fold]

In [44]:
dic = {"a" : 5, "b": 8}

In [49]:
d = dic.keys()
d

dict_keys(['a', 'b'])

In [51]:
list(d)

['a', 'b']

In [52]:
type(d)

dict_keys