In [2]:
import numpy as np


In [3]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
a

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [4]:
mask1 = np.arange(6)
mask2 = [1, 3, 6, 3, 1, 3]
print(mask1)
print(mask2)

[0 1 2 3 4 5]
[1, 3, 6, 3, 1, 3]


In [5]:
b = a[mask1, mask2]
b

array([2, 4, 7, 4, 2, 4])

In [6]:
b.reshape(a.shape[0], 1)

array([[2],
       [4],
       [7],
       [4],
       [2],
       [4]])

In [7]:
a[mask1, mask2] = 0

In [8]:
a

array([[1, 0, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 0],
       [1, 2, 3, 0, 5, 6, 7],
       [1, 0, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 5, 6, 7]])

In [9]:
a[a > 0] = 1.0

In [10]:
a

array([[1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1]])

In [11]:
row_sum = np.sum(a, axis=1)
row_sum

array([6, 6, 6, 6, 6, 6])

In [12]:
a[mask1, mask2] -= row_sum

In [13]:
a

array([[ 1, -6,  1,  1,  1,  1,  1],
       [ 1,  1,  1, -6,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1, -6],
       [ 1,  1,  1, -6,  1,  1,  1],
       [ 1, -6,  1,  1,  1,  1,  1],
       [ 1,  1,  1, -6,  1,  1,  1]])

In [14]:
y_pred = np.argmin(a, axis = 1)
y_pred

array([1, 3, 6, 3, 1, 3], dtype=int64)

In [17]:
f = np.array([123, 456, 789]) # example with 3 classes and each having large scores
p = np.exp(f) / np.sum(np.exp(f))
p

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ 0.,  0., nan])

In [18]:
# instead: first shift the values of f so that the highest number is 0:
f -= np.max(f) # f becomes [-666, -333, 0]
p = np.exp(f) / np.sum(np.exp(f))
p

array([5.75274406e-290, 2.39848787e-145, 1.00000000e+000])